#!/usr/bin/env python3
"""
Generate web/rytt-data.js and fixtures/rytt_vocabulary.json from compiler definitions.
Run: python scripts/generate_web_data.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from rytt import __version__
from rytt.compiler import RYTT_GENOME, RYTT_LIGATURES, PUA_TO_PLAIN

ROOT = Path(__file__).resolve().parents[1]
WEB_DIR = ROOT / "web"
FIXTURES_DIR = ROOT / "fixtures"
WEB_DIR.mkdir(exist_ok=True)
FIXTURES_DIR.mkdir(exist_ok=True)

# Build vocabulary JSON
vocab = {
    "version": __version__,
    "genome": {
        k: {
            "pua": v["pua"],
            "pua_codepoint": hex(ord(v["pua"])),
            "family": v["family"],
            "vowel": v.get("vowel", False),
            "is_upper": v["is_upper"],
            "case_plane": v["case_plane"],
            "elevation_z": v["elevation_z"],
            "trit_val": v.get("trit_val", 0),
            "sept_val": v.get("sept_val", 0),
        }
        for k, v in RYTT_GENOME.items()
    },
    "ligatures": {
        k: {
            "pua": v["pua"],
            "pua_codepoint": hex(ord(v["pua"])),
            "meaning": v["meaning"],
            "is_upper": v["is_upper"],
            "case_plane": v["case_plane"],
            "elevation_z": v["elevation_z"],
        }
        for k, v in RYTT_LIGATURES.items()
    },
    "pua_to_plain": {hex(ord(k)): v for k, v in PUA_TO_PLAIN.items()},
    "stats": {
        "genome_entries": len(RYTT_GENOME),
        "ligature_entries": len(RYTT_LIGATURES),
        "pua_mappings": len(PUA_TO_PLAIN),
    },
}
vocab_path = FIXTURES_DIR / "rytt_vocabulary.json"
vocab_path.write_text(json.dumps(vocab, ensure_ascii=False, indent=2))
print(f"Written: {vocab_path}")

# Build JS data module
genome_js_entries = []
for k, v in RYTT_GENOME.items():
    genome_js_entries.append(
        f"  {json.dumps(k)}: {{"
        f"pua:{json.dumps(v['pua'])}, family:{json.dumps(v['family'])}, "
        f"vowel:{str(v.get('vowel', False)).lower()}, isUpper:{str(v['is_upper']).lower()}, "
        f"casePlane:{v['case_plane']}, elevationZ:{v['elevation_z']}, "
        f"tritVal:{v.get('trit_val', 0)}, septVal:{v.get('sept_val', 0)}, "
        f"path:{json.dumps(v.get('path', ''))}}}"
    )

lig_js_entries = []
for k, v in RYTT_LIGATURES.items():
    lig_js_entries.append(
        f"  {json.dumps(k)}: {{"
        f"pua:{json.dumps(v['pua'])}, meaning:{json.dumps(v['meaning'])}, "
        f"isUpper:{str(v['is_upper']).lower()}, casePlane:{v['case_plane']}, "
        f"elevationZ:{v['elevation_z']}, path:{json.dumps(v.get('path', ''))}}}"
    )

pua_js_entries = [
    f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in PUA_TO_PLAIN.items()
]

js_content = f"""// AUTO-GENERATED by scripts/generate_web_data.py — DO NOT EDIT
// RYTT Sovereign Semiotics v{__version__} — Compiler Data for Browser Playground
/* eslint-disable */

export const RYTT_VERSION = "{__version__}";

export const RYTT_GENOME = {{
{chr(44)+chr(10).join(genome_js_entries)}
}};

export const RYTT_LIGATURES = {{
{chr(44)+chr(10).join(lig_js_entries)}
}};

export const PUA_TO_PLAIN = {{
{chr(44)+chr(10).join(pua_js_entries)}
}};

export const RYTT_STATS = {{
  genomeEntries: {len(RYTT_GENOME)},
  ligatureEntries: {len(RYTT_LIGATURES)},
  puaMappings: {len(PUA_TO_PLAIN)},
}};
"""
js_path = WEB_DIR / "rytt-data.js"
js_path.write_text(js_content)
print(f"Written: {js_path}")
print("Done.")
