// AUTO-GENERATED by scripts/generate_web_data.py — DO NOT EDIT
// RYTT Sovereign Semiotics v0.1.0 — Compiler Data for Browser Playground
// Full data is generated by running: python scripts/generate_web_data.py
// Commit the generated file after running the script locally or via CI.
/* eslint-disable */

export const RYTT_VERSION = "0.1.0";
export const RYTT_STATS = { genomeEntries: 52, ligatureEntries: 46, puaMappings: 98 };
