// AUTO-GENERATED by scripts/generate_web_data.py — DO NOT EDIT
// RYTT Sovereign Semiotics v0.1.0 — Compiler Data for Browser Playground
/* eslint-disable */

export const RYTT_VERSION = "0.1.0";

export const RYTT_GENOME = {
,  "A": {pua:"\ue800", family:"POINT", vowel:true, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:0, septVal:0, path:"M 50,50 m -6,0 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0"}
  "a": {pua:"\ue000", family:"POINT", vowel:true, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:0, septVal:0, path:"M 50,50 m -6,0 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0"}
  "B": {pua:"\ue801", family:"VECTOR", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:1, path:"M 50,20 L 50,80 M 50,50 L 75,50 M 50,32 L 68,32"}
  "b": {pua:"\ue001", family:"VECTOR", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:1, path:"M 50,20 L 50,80 M 50,50 L 75,50 M 50,32 L 68,32"}
  "C": {pua:"\ue802", family:"CHEVRON", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:-1, path:"M 70,25 L 35,50 L 70,75"}
  "c": {pua:"\ue002", family:"CHEVRON", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:-1, path:"M 70,25 L 35,50 L 70,75"}
  "D": {pua:"\ue803", family:"CHEVRON", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:2, path:"M 70,25 L 35,50 L 70,75 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "d": {pua:"\ue003", family:"CHEVRON", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:2, path:"M 70,25 L 35,50 L 70,75 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "E": {pua:"\ue804", family:"DIAMOND", vowel:true, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:0, septVal:-2, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "e": {pua:"\ue004", family:"DIAMOND", vowel:true, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:0, septVal:-2, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "F": {pua:"\ue805", family:"DIAMOND", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:3, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z"}
  "f": {pua:"\ue005", family:"DIAMOND", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:3, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z"}
  "G": {pua:"\ue806", family:"VECTOR", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:-3, path:"M 20,50 L 80,50"}
  "g": {pua:"\ue006", family:"VECTOR", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:-3, path:"M 20,50 L 80,50"}
  "H": {pua:"\ue807", family:"FRAME", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:1, path:"M 30,80 L 30,20 L 80,20"}
  "h": {pua:"\ue007", family:"FRAME", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:1, path:"M 30,80 L 30,20 L 80,20"}
  "I": {pua:"\ue808", family:"FRAME", vowel:true, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:0, septVal:0, path:"M 75,25 L 30,25 L 30,75 L 75,75 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "i": {pua:"\ue008", family:"FRAME", vowel:true, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:0, septVal:0, path:"M 75,25 L 30,25 L 30,75 L 75,75 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "J": {pua:"\ue809", family:"FRAME", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:2, path:"M 75,25 L 30,25 L 30,75 L 75,75"}
  "j": {pua:"\ue009", family:"FRAME", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:2, path:"M 75,25 L 30,25 L 30,75 L 75,75"}
  "K": {pua:"\ue80a", family:"FRAME", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:-2, path:"M 25,25 L 75,25 L 75,75 L 25,75 Z"}
  "k": {pua:"\ue00a", family:"FRAME", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:-2, path:"M 25,25 L 75,25 L 75,75 L 25,75 Z"}
  "L": {pua:"\ue80b", family:"ARC", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:3, path:"M 70,25 A 30,30 0 0,0 70,75"}
  "l": {pua:"\ue00b", family:"ARC", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:3, path:"M 70,25 A 30,30 0 0,0 70,75"}
  "M": {pua:"\ue80c", family:"ARC", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:-3, path:"M 25,70 A 30,30 0 0,1 75,70"}
  "m": {pua:"\ue00c", family:"ARC", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:-3, path:"M 25,70 A 30,30 0 0,1 75,70"}
  "N": {pua:"\ue80d", family:"ARC", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:1, path:"M 35,25 A 25,25 0 0,0 35,75 M 65,25 A 25,25 0 0,1 65,75"}
  "n": {pua:"\ue00d", family:"ARC", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:1, path:"M 35,25 A 25,25 0 0,0 35,75 M 65,25 A 25,25 0 0,1 65,75"}
  "O": {pua:"\ue80e", family:"ARC", vowel:true, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:0, septVal:0, path:"M 35,25 A 25,25 0 0,0 35,75 M 65,25 A 25,25 0 0,1 65,75 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "o": {pua:"\ue00e", family:"ARC", vowel:true, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:0, septVal:0, path:"M 35,25 A 25,25 0 0,0 35,75 M 65,25 A 25,25 0 0,1 65,75 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "P": {pua:"\ue80f", family:"ARC", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:2, path:"M 20,25 A 35,25 0 0,0 20,75 M 80,25 A 35,25 0 0,1 80,75"}
  "p": {pua:"\ue00f", family:"ARC", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:2, path:"M 20,25 A 35,25 0 0,0 20,75 M 80,25 A 35,25 0 0,1 80,75"}
  "Q": {pua:"\ue810", family:"RING", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:-2, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0"}
  "q": {pua:"\ue010", family:"RING", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:-2, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0"}
  "R": {pua:"\ue811", family:"RING", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:3, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "r": {pua:"\ue011", family:"RING", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:3, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0 M 50,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "S": {pua:"\ue812", family:"VECTOR", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:-3, path:"M 50,20 L 50,80"}
  "s": {pua:"\ue012", family:"VECTOR", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:-3, path:"M 50,20 L 50,80"}
  "T": {pua:"\ue813", family:"VECTOR", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:1, path:"M 20,20 L 80,20 M 50,20 L 50,80"}
  "t": {pua:"\ue013", family:"VECTOR", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:1, path:"M 20,20 L 80,20 M 50,20 L 50,80"}
  "U": {pua:"\ue814", family:"VECTOR", vowel:true, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:0, septVal:0, path:"M 40,20 L 40,80 M 65,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "u": {pua:"\ue014", family:"VECTOR", vowel:true, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:0, septVal:0, path:"M 40,20 L 40,80 M 65,50 m -5,0 a 5,5 0 1,0 10,0 a 5,5 0 1,0 -10,0"}
  "V": {pua:"\ue815", family:"CHEVRON", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:2, path:"M 25,25 L 50,75 L 75,25"}
  "v": {pua:"\ue015", family:"CHEVRON", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:2, path:"M 25,25 L 50,75 L 75,25"}
  "W": {pua:"\ue816", family:"CHEVRON", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:-2, path:"M 20,25 L 50,75 L 80,25 M 35,50 L 65,50"}
  "w": {pua:"\ue016", family:"CHEVRON", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:-2, path:"M 20,25 L 50,75 L 80,25 M 35,50 L 65,50"}
  "X": {pua:"\ue817", family:"VECTOR", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:3, path:"M 25,25 L 75,75 M 75,25 L 25,75"}
  "x": {pua:"\ue017", family:"VECTOR", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:3, path:"M 25,25 L 75,75 M 75,25 L 25,75"}
  "Y": {pua:"\ue818", family:"BRANCH", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:1, septVal:-3, path:"M 25,25 L 50,50 L 75,25 M 50,50 L 50,80"}
  "y": {pua:"\ue018", family:"BRANCH", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:1, septVal:-3, path:"M 25,25 L 50,50 L 75,25 M 50,50 L 50,80"}
  "Z": {pua:"\ue819", family:"BRANCH", vowel:false, isUpper:true, casePlane:1, elevationZ:25.0, tritVal:-1, septVal:1, path:"M 50,80 L 50,20 M 30,40 L 50,20 L 70,40"}
  "z": {pua:"\ue019", family:"BRANCH", vowel:false, isUpper:false, casePlane:0, elevationZ:0.0, tritVal:-1, septVal:1, path:"M 50,80 L 50,20 M 30,40 L 50,20 L 70,40"}
};

export const RYTT_LIGATURES = {
,  "TION": {pua:"\ue840", meaning:"Process / State", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 35,50 A 15,15 0 1,0 65,50 A 15,15 0 1,0 35,50"}
  "tion": {pua:"\ue040", meaning:"Process / State", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 35,50 A 15,15 0 1,0 65,50 A 15,15 0 1,0 35,50"}
  "MENT": {pua:"\ue841", meaning:"Artifact / Entity", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 25,70 A 30,30 0 0,1 75,70 M 50,20 L 80,50 L 50,80 L 20,50 Z"}
  "ment": {pua:"\ue041", meaning:"Artifact / Entity", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 25,70 A 30,30 0 0,1 75,70 M 50,20 L 80,50 L 50,80 L 20,50 Z"}
  "RYTT": {pua:"\ue842", meaning:"Sovereign Inscription Seal", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0 M 20,20 L 80,20 M 50,20 L 50,80 M 35,50 L 65,50"}
  "rytt": {pua:"\ue042", meaning:"Sovereign Inscription Seal", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0 M 20,20 L 80,20 M 50,20 L 50,80 M 35,50 L 65,50"}
  "PSY": {pua:"\ue820", meaning:"Mind / Intent / Vector", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,20 L 50,80 M 20,40 L 50,60 L 80,40 M 25,25 L 75,25"}
  "psy": {pua:"\ue020", meaning:"Mind / Intent / Vector", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,20 L 50,80 M 20,40 L 50,60 L 80,40 M 25,25 L 75,25"}
  "STR": {pua:"\ue821", meaning:"Structure / Lattice", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 20,80 L 80,80 M 20,20 L 80,80"}
  "str": {pua:"\ue021", meaning:"Structure / Lattice", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 20,80 L 80,80 M 20,20 L 80,80"}
  "ING": {pua:"\ue822", meaning:"Continuous Action", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 20,50 L 80,50"}
  "ing": {pua:"\ue022", meaning:"Continuous Action", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 20,50 L 80,50"}
  "ALL": {pua:"\ue823", meaning:"Totality / Universe", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,50 m -30,0 a 30,30 0 1,0 60,0 a 30,30 0 1,0 -60,0 M 50,20 L 50,80"}
  "all": {pua:"\ue023", meaning:"Totality / Universe", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,50 m -30,0 a 30,30 0 1,0 60,0 a 30,30 0 1,0 -60,0 M 50,20 L 50,80"}
  "THE": {pua:"\ue824", meaning:"Definite Ground Truth", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 30,80 L 30,40 L 70,40 L 70,80"}
  "the": {pua:"\ue024", meaning:"Definite Ground Truth", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 30,80 L 30,40 L 70,40 L 70,80"}
  "AND": {pua:"\ue825", meaning:"Conjunction / Tensor Product", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,50 m -6,0 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0 M 70,25 L 35,50 L 70,75"}
  "and": {pua:"\ue025", meaning:"Conjunction / Tensor Product", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,50 m -6,0 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0 M 70,25 L 35,50 L 70,75"}
  "NOT": {pua:"\ue826", meaning:"Negation / Mirror Inversion", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,20 L 80,80 M 80,20 L 20,80 M 50,50 m -15,0 a 15,15 0 1,0 30,0 a 15,15 0 1,0 -30,0"}
  "not": {pua:"\ue026", meaning:"Negation / Mirror Inversion", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,20 L 80,80 M 80,20 L 20,80 M 50,50 m -15,0 a 15,15 0 1,0 30,0 a 15,15 0 1,0 -30,0"}
  "FOR": {pua:"\ue827", meaning:"Iteration / Purpose Loop", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0"}
  "for": {pua:"\ue027", meaning:"Iteration / Purpose Loop", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0"}
  "CON": {pua:"\ue828", meaning:"Convergence / Collective", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 70,25 L 35,50 L 70,75 M 50,50 m -15,0 a 15,15 0 1,0 30,0 a 15,15 0 1,0 -30,0"}
  "con": {pua:"\ue028", meaning:"Convergence / Collective", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 70,25 L 35,50 L 70,75 M 50,50 m -15,0 a 15,15 0 1,0 30,0 a 15,15 0 1,0 -30,0"}
  "PRO": {pua:"\ue829", meaning:"Forward Projection", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,25 A 35,25 0 0,0 20,75 M 80,25 A 35,25 0 0,1 80,75 M 50,50 m -10,0 a 10,10 0 1,0 20,0 a 10,10 0 1,0 -20,0"}
  "pro": {pua:"\ue029", meaning:"Forward Projection", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,25 A 35,25 0 0,0 20,75 M 80,25 A 35,25 0 0,1 80,75 M 50,50 m -10,0 a 10,10 0 1,0 20,0 a 10,10 0 1,0 -20,0"}
  "TH": {pua:"\ue830", meaning:"Aspiration / Horizon", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 50,50 L 80,50 L 80,80"}
  "th": {pua:"\ue030", meaning:"Aspiration / Horizon", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 50,50 L 80,50 L 80,80"}
  "ST": {pua:"\ue831", meaning:"Standing State", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 35,50 L 65,50"}
  "st": {pua:"\ue031", meaning:"Standing State", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 20,20 L 80,20 M 50,20 L 50,80 M 35,50 L 65,50"}
  "IN": {pua:"\ue832", meaning:"Interior Admission", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 65,25 A 25,25 0 0,0 65,75 M 85,25 A 25,25 0 0,1 85,75 M 45,35 L 20,35 L 20,65 L 45,65"}
  "in": {pua:"\ue032", meaning:"Interior Admission", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 65,25 A 25,25 0 0,0 65,75 M 85,25 A 25,25 0 0,1 85,75 M 45,35 L 20,35 L 20,65 L 45,65"}
  "EE": {pua:"\ue833", meaning:"Twin Resonant Eye", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 35,20 L 65,50 L 35,80 L 05,50 Z M 35,50 m -4,0 a 4,4 0 1,0 8,0 a 4,4 0 1,0 -8,0 M 65,20 L 95,50 L 65,80 L 35,50 Z M 65,50 m -4,0 a 4,4 0 1,0 8,0 a 4,4 0 1,0 -8,0"}
  "ee": {pua:"\ue033", meaning:"Twin Resonant Eye", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 35,20 L 65,50 L 35,80 L 05,50 Z M 35,50 m -4,0 a 4,4 0 1,0 8,0 a 4,4 0 1,0 -8,0 M 65,20 L 95,50 L 65,80 L 35,50 Z M 65,50 m -4,0 a 4,4 0 1,0 8,0 a 4,4 0 1,0 -8,0"}
  "ER": {pua:"\ue834", meaning:"Agent / Operator", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 50,50 m -15,0 a 15,15 0 1,0 30,0 a 15,15 0 1,0 -30,0"}
  "er": {pua:"\ue034", meaning:"Agent / Operator", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,20 L 80,50 L 50,80 L 20,50 Z M 50,50 m -15,0 a 15,15 0 1,0 30,0 a 15,15 0 1,0 -30,0"}
  "ON": {pua:"\ue835", meaning:"Ontological Presence", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 35,25 A 25,25 0 0,0 35,75 M 65,25 A 25,25 0 0,1 65,75 M 50,50 m -10,0 a 10,10 0 1,0 20,0 a 10,10 0 1,0 -20,0"}
  "on": {pua:"\ue035", meaning:"Ontological Presence", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 35,25 A 25,25 0 0,0 35,75 M 65,25 A 25,25 0 0,1 65,75 M 50,50 m -10,0 a 10,10 0 1,0 20,0 a 10,10 0 1,0 -20,0"}
  "AT": {pua:"\ue836", meaning:"Locality / Coordinate", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,50 m -6,0 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0 M 20,20 L 80,20 M 50,20 L 50,80"}
  "at": {pua:"\ue036", meaning:"Locality / Coordinate", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,50 m -6,0 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0 M 20,20 L 80,20 M 50,20 L 50,80"}
  "RY": {pua:"\ue837", meaning:"Sovereign Root Sign", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0 M 25,25 L 50,50 L 75,25 M 50,50 L 50,80"}
  "ry": {pua:"\ue037", meaning:"Sovereign Root Sign", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,50 m -25,0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50,0 M 25,25 L 50,50 L 75,25 M 50,50 L 50,80"}
  "TT": {pua:"\ue838", meaning:"Dual Pillar Invariant", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 15,20 L 45,20 M 30,20 L 30,80 M 55,20 L 85,20 M 70,20 L 70,80"}
  "tt": {pua:"\ue038", meaning:"Dual Pillar Invariant", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 15,20 L 45,20 M 30,20 L 30,80 M 55,20 L 85,20 M 70,20 L 70,80"}
  "RE": {pua:"\ue839", meaning:"Recursive Return", isUpper:true, casePlane:1, elevationZ:25.0, path:"M 50,50 m -20,0 a 20,20 0 1,0 40,0 a 20,20 0 1,0 -40,0 M 50,30 L 70,50 L 50,70 L 30,50 Z"}
  "re": {pua:"\ue039", meaning:"Recursive Return", isUpper:false, casePlane:0, elevationZ:0.0, path:"M 50,50 m -20,0 a 20,20 0 1,0 40,0 a 20,20 0 1,0 -40,0 M 50,30 L 70,50 L 50,70 L 30,50 Z"}
};

export const PUA_TO_PLAIN = {
,  "\ue800": "A"
  "\ue000": "a"
  "\ue801": "B"
  "\ue001": "b"
  "\ue802": "C"
  "\ue002": "c"
  "\ue803": "D"
  "\ue003": "d"
  "\ue804": "E"
  "\ue004": "e"
  "\ue805": "F"
  "\ue005": "f"
  "\ue806": "G"
  "\ue006": "g"
  "\ue807": "H"
  "\ue007": "h"
  "\ue808": "I"
  "\ue008": "i"
  "\ue809": "J"
  "\ue009": "j"
  "\ue80a": "K"
  "\ue00a": "k"
  "\ue80b": "L"
  "\ue00b": "l"
  "\ue80c": "M"
  "\ue00c": "m"
  "\ue80d": "N"
  "\ue00d": "n"
  "\ue80e": "O"
  "\ue00e": "o"
  "\ue80f": "P"
  "\ue00f": "p"
  "\ue810": "Q"
  "\ue010": "q"
  "\ue811": "R"
  "\ue011": "r"
  "\ue812": "S"
  "\ue012": "s"
  "\ue813": "T"
  "\ue013": "t"
  "\ue814": "U"
  "\ue014": "u"
  "\ue815": "V"
  "\ue015": "v"
  "\ue816": "W"
  "\ue016": "w"
  "\ue817": "X"
  "\ue017": "x"
  "\ue818": "Y"
  "\ue018": "y"
  "\ue819": "Z"
  "\ue019": "z"
  "\ue840": "TION"
  "\ue040": "tion"
  "\ue841": "MENT"
  "\ue041": "ment"
  "\ue842": "RYTT"
  "\ue042": "rytt"
  "\ue820": "PSY"
  "\ue020": "psy"
  "\ue821": "STR"
  "\ue021": "str"
  "\ue822": "ING"
  "\ue022": "ing"
  "\ue823": "ALL"
  "\ue023": "all"
  "\ue824": "THE"
  "\ue024": "the"
  "\ue825": "AND"
  "\ue025": "and"
  "\ue826": "NOT"
  "\ue026": "not"
  "\ue827": "FOR"
  "\ue027": "for"
  "\ue828": "CON"
  "\ue028": "con"
  "\ue829": "PRO"
  "\ue029": "pro"
  "\ue830": "TH"
  "\ue030": "th"
  "\ue831": "ST"
  "\ue031": "st"
  "\ue832": "IN"
  "\ue032": "in"
  "\ue833": "EE"
  "\ue033": "ee"
  "\ue834": "ER"
  "\ue034": "er"
  "\ue835": "ON"
  "\ue035": "on"
  "\ue836": "AT"
  "\ue036": "at"
  "\ue837": "RY"
  "\ue037": "ry"
  "\ue838": "TT"
  "\ue038": "tt"
  "\ue839": "RE"
  "\ue039": "re"
};

export const RYTT_STATS = {
  genomeEntries: 52,
  ligatureEntries: 46,
  puaMappings: 98,
};
